"""
Telemetry and Operational Event schemas for AegisOps.
Uses Pydantic v2 for data validation, serialization, and schema definition.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class SeverityLevel(str, Enum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class IncidentStatus(str, Enum):
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    MITIGATING = "MITIGATING"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class SystemTelemetry(BaseModel):
    """Real-time host telemetry snapshot."""
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    host_name: str = "localhost"
    cpu_percent: float = Field(..., ge=0.0, le=100.0, description="Host CPU utilization percentage")
    memory_percent: float = Field(..., ge=0.0, le=100.0, description="RAM utilization percentage")
    memory_used_gb: float = Field(default=0.0, description="Used RAM in Gigabytes")
    memory_total_gb: float = Field(default=0.0, description="Total RAM in Gigabytes")
    disk_percent: float = Field(..., ge=0.0, le=100.0, description="Root partition disk utilization")
    disk_free_gb: float = Field(default=0.0, description="Free disk in Gigabytes")
    network_sent_mb: float = Field(default=0.0, description="Megabytes sent since boot")
    network_recv_mb: float = Field(default=0.0, description="Megabytes received since boot")
    process_count: int = Field(default=0, ge=0, description="Number of active processes")

    model_config = {
        "json_encoders": {datetime: lambda v: v.isoformat()}
    }


class AnomalyScore(BaseModel):
    """Telemetry anomaly evaluation generated by scikit-learn detector."""
    is_anomaly: bool = False
    score: float = Field(default=0.0, description="Anomaly score metric where negative or elevated values denote outliers")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Statistical confidence in detection")
    anomaly_type: Optional[str] = None
    affected_metrics: List[str] = Field(default_factory=list)
    description: str = "System telemetry within expected operating baseline"


class LLMAnalysisResult(BaseModel):
    """Structured output from LLM Root Cause Analysis service."""
    summary: str
    probable_root_cause: str
    suggested_mitigation_steps: List[str]
    confidence: float = Field(default=0.85, ge=0.0, le=1.0)
    provider: str = "mock"
    raw_response: Optional[str] = None


class IncidentReport(BaseModel):
    """High-level incident report generated from telemetry and AI triage."""
    id: str
    title: str
    description: str
    severity: SeverityLevel = SeverityLevel.LOW
    status: IncidentStatus = IncidentStatus.OPEN
    anomaly_score: Optional[AnomalyScore] = None
    ai_analysis: Optional[LLMAnalysisResult] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = Field(default_factory=dict)


class RemediationAction(BaseModel):
    """Autonomous or operator-approved remediation action."""
    action_id: str
    incident_id: str
    action_name: str
    description: str
    status: str = "PENDING"
    automated: bool = True
    executed_at: Optional[datetime] = None
    result_message: Optional[str] = None
